# Generated by Django 2.1.7 on 2026-02-25 06:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category', models.CharField(choices=[('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Grains', 'Grains'), ('Dairy', 'Dairy'), ('Other', 'Other')], default='Other', max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('origin_location', models.CharField(blank=True, max_length=300)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('blockchain_hash', models.CharField(blank=True, max_length=255)),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('blockchain_hash', models.CharField(blank=True, max_length=255)),
                ('purchased_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='TransportLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('Harvested', 'Harvested'), ('Packed', 'Packed'), ('InTransit', 'In Transit'), ('AtWarehouse', 'At Warehouse'), ('Delivered', 'Delivered')], max_length=20)),
                ('location', models.CharField(max_length=300)),
                ('handler', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_logs', to='AgricultureApp.Product')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('user_type', models.CharField(choices=[('Admin', 'Admin'), ('Farmer', 'Farmer'), ('Consumer', 'Consumer')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('blockchain_hash', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='consumer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'Consumer'}, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='AgricultureApp.UserProfile'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='farmer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'Farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='AgricultureApp.UserProfile'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='AgricultureApp.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='farmer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'Farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='AgricultureApp.UserProfile'),
        ),
    ]
